buggy_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'buggy_app'

urlpatterns = [

    url(r'^carlist$',views.CarListView.as_view(),name='car_list'),
    url(r'^(?P<pk>\d+)/$',views.CarDetailView.as_view(),name='details'),
    #url(r'^(?P<pk>\d+)/book$',views.booking_create,name='booking_create'),
    url('booking/',views.BookingView.as_view(),name='car_booking'),




]

joinbuggy/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from buggy_app import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^buggy_app/',include('buggy_app.urls',namespace='buggy_app')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buggy_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone


class Color(models.Model):
    name = models.CharField(max_length=16)
    hex = models.CharField(max_length=16)
    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=16)
    def __str__(self):
        return self.name


class Times(models.Model):
    time_type = models.CharField(max_length = 30)
    timeslot= models.TimeField(blank = True)
    time_check= models.BooleanField(default = True)

    def __str__(self):
        return self.time_type




class Car(models.Model):
    TRANSMISSION_CHOICES = (
        ('Auto', 'Auto'),
        ('Manual', 'Manual')
    )
    SEATS_CHOICES = (
        ('2', '2'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        )
    FUEL_CHECK = (
        ('Petrol', 'PETROL'),
        ('Diesel', 'Diesel'),
        ('Gas', 'Gas'),
    )
    reg_no = models.CharField(max_length=16, unique=True)
    model_year = models.DateField()
    car_name =models.CharField(max_length=40)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    times_for = models.ForeignKey(Times,on_delete=models.CASCADE)
    car_image = models.ImageField(upload_to='cars', blank = True)
    description = models.CharField(max_length=200)
    is_available_car = models.BooleanField(default = False)
    car_price = models.IntegerField(blank = False)
    power_hp = models.CharField(max_length= 20 , blank = True)
    transmission = models.CharField(max_length = 10 , choices = TRANSMISSION_CHOICES)
    seats = models.CharField(max_length=10, choices = SEATS_CHOICES)
    air_bags = models.CharField (max_length = 10 , choices = SEATS_CHOICES)
    car_image_internal = models.ImageField(upload_to='cars', blank = True)
    car_image_internal2 = models.ImageField(upload_to='cars', blank = True)
    fuel_type = models.CharField(max_length= 20 , choices = FUEL_CHECK)

    def __str__(self):
        return self.car_name

    def get_absolute_url(self):
        return reverse("buggy_app:details",kwargs={'pk':self.pk})



class Customer(models.Model):
    first_name = models.CharField(max_length=64,null= False)
    last_name = models.CharField(max_length=64)
    customer_age = models.IntegerField(blank=True, null=True)
    last_name = models.CharField(blank=True, max_length=100)
    license_year = models.IntegerField(blank=False, null=False)
    tlc_number = models.IntegerField(blank=False ,null=False)
    contact_num =models.IntegerField(blank=False, null=False)
    contact_email = models.EmailField(blank =False)


    def __str__(self):
        return self.first_name


class Booking(models.Model):
    booking_name = models.CharField(max_length=240,null= False)
    customer_name = models.ForeignKey(Customer ,on_delete=models.CASCADE,related_name='book_customers' )
    book_car = models.ForeignKey(Car, on_delete=models.CASCADE ,related_name='book_car')
    booking_start_date = models.DateTimeField(auto_now_add=True ,blank=True)
    booking_end_date = models.DateTimeField(blank = True , null = True)
    rental_price = models.IntegerField(blank=False, null=False)
    is_approved = models.BooleanField(default=False)
    def __str__(self):
        return self.booking_name

    def get_absolute_url(self):
        return reverse("buggy_app:detail",kwargs={'pk':self.pk})

buggy_app/forms.py
from django import forms

buggy_app/views.py
from django.shortcuts import render ,redirect , get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)

from .  import models
from buggy_app.models import Booking , Car
from django.forms import ModelForm
from django.views.generic.edit import FormView


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = ('booking_name','rental_price','book_car','customer_name',)




class IndexView(TemplateView):

    template_name = 'buggy_app/index.html'




'''
class BookingListView(ListView):

    model = models.Booking


class BookingDetailView(DetailView):
    context_object_name = 'booking_details'
    model = models.Booking
    template_name = 'buggy_app/booking_detail.html'


class BookingCreateView(CreateView):
    fields = ("customer_name","book_car","booking_end_date","rental_price","is_approved")
    model = models.Booking


class BookingUpdateView(UpdateView):
    fields = ("customer_name","book_car","booking_end_date","rental_price","is_approved")
    model = models.Booking
'''

class CarListView(ListView):
    context_object_name = 'cars'
    model = models.Car

class CarDetailView(DetailView):
    context_object_name = 'car_details'
    model = models.Car
    template_name = 'buggy_app/car_detail.html'




class BookingView(FormView):
    template_name = 'buggy_app/booking.html'
    form_class = BookingForm

class BookingView(FormView):
    template_name = 'buggy_app/booking.html'
    form_class = BookingForm

    def get_context_data(self, **kwargs):
        # kwargs['car'] is the car booking now!
        try:
            kwargs['car'] = Car.objects.get(id=self.request.GET.get('car', ''))
        except (Car.DoesNotExist, ValueError):
            kwargs['car'] = None
        return super(BookingView, self).get_context_data(**kwargs)

    # if you still want to keep select car in form,and auto select this car do as:
    def get_initial(self):
        initial = super(BookingView, self).get_initial()
        if 'car' in self.request.GET:
            try:
                initial['book_car'] = Car.objects.get(id=self.request.GET['car'])
            except (Car.DoesNotExist, ValueError):
                pass
        return initial



'''
def booking_create(request,pk):
    book_car = get_object_or_404(Car, pk=pk)
    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():

            booking = form.save(commit=False)
            booking.book_car = book_car
            booking.save()
            return redirect('car_detail', pk=book_car.pk)
    else:
        form = BookingForm()
    return render(request, 'buggy_app/booking_form.html', {'form': form})
'''

templates/buggy_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">



    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      Buggy
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>
    <link rel="shortcut icon" type="image/x-icon" href="https://static1.squarespace.com/static/54baaa4ae4b0ff95698b489f/t/55b0d9d5e4b0b5f727d48e94/favicon.ico">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  	<meta charset="utf-8">
  	<meta http-equiv="x-ua-compatible" content="ie=edge">
  	<title></title>
  	<meta name="description" content="">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  	<link rel="manifest" href="site.webmanifest">
  	<link rel="apple-touch-icon" href="icon.png">



  <link  rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link href="{% static 'css/nouislider.css' %}"rel="stylesheet">
<link href="{% static 'css/nouislider.pips.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">





</head>
  <body>


    <nav class="navbar navbar-expand-md navbar-light bg-light">
    	<div class="container-fluid">
    		<a class="navbar-brand" href="{% url 'index' %}"><img src ="{% static "img/buggy.png" %}"</a>
    		<button class="navbar-toggler" type="button" data-toggle="collapse"
    		data-target="#navbarResponsive">
    			<span class="navbar-toggler-icon"></span>
    		</button>
    		<div class="collapse navbar-collapse" id="navbarResponsive">
    			 <ul class="navbar-nav ml-auto">
    					 <a class="nav-link" href="#"></a>

    				 <li class="nav-item active" >
    					 <a class="nav-link" href="{% url 'index' %}">Home</a>
    					 </li>
             <li class="nav-item">
      								 <a class="nav-link" href="{% url 'buggy_app:car_list' %}">list</a>
      								 </li>

    			 </ul>

    		</div>
    	</div>
    </nav>



      {% block body_block %}

      {% endblock %}

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.2.0.min.js"
  integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
  crossorigin="anonymous"></script>


</html>

templates/buggy_app/booking.html
{% extends "buggy_app/base.html" %}
{% load static from staticfiles %}
{% load bootstrap4 %}
{% block body_block %}
<body>
  <div class="container">
      <div class="container">
        <div class="container">




  <form method="POST">
    {% csrf_token %}
      {% bootstrap_form form %}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>

</div>
</div>
</div>

{% endblock %}

templates/buggy_app/booking_list.html
{% extends "buggy_app/base.html" %}


{% block body_block %}
{% load staticfiles %}
<div class="container">



  <div class="jumbotron">

    <h1>Welcome to the list of Booking </h1>


  </div>

  <div class="col-12">

  <img src="{% static "img/bg.png" %}" class="img-fluid" alt="Responsive image">
  </div>
  <div style="width : 50%">
    <div class="container">


    <table class="table table-hover table-dark">

      <thead>
        <tr style="border : 1px solid black">
          <td style="border : 1px solid black" ><h2>ID</h2></td>
          <td style="border : 1px solid black"><h2>NAME</h2></td>
        </tr>
      </thead>
    {% for book in booking_list %}
    <tbody>
    <tr style="border : 1px solid black">
        <td style="border : 1px solid black">
          <h2>{{book.id}}</h2>
        </td>
        <td style="border : 1px solid white">
          <h2><a href="{{book.id}}/">{{book.customer_name}} </a></h2>
        </td>
    </tr>
    </tbody>
    {% endfor %}
    </table>
    </div>
  </div>
    </div>
{% endblock %}

templates/buggy_app/car_detail.html
{% extends "buggy_app/base.html" %}


{% block body_block %}
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/style1.css' %}">

        <!--Car Details-->
    <div class="single-car car-details">
        <div class="auto-container">
        	<!--Basic Details-->
            <div class="basic-details">
            	<div class="row clearfix">
                	<!--Carousel Column-->
                    <div class="carousel-column col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    	<!--Product Carousel-->
                      <div id="myCarousel" class="carousel slide" data-ride="carousel">
       <!-- Indicators -->
       <ol class="carousel-indicators">
         <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
         <li data-target="#myCarousel" data-slide-to="1"></li>
         <li data-target="#myCarousel" data-slide-to="2"></li>
       </ol>

       <!-- Wrapper for slides -->
       <div class="carousel-inner">
         <div class="item active">
           <img src="{{car_details.car_image.url}}" alt="Los Angeles" style="width:100%;">
         </div>

         <div class="item">
           <img src="{{car_details.car_image_internal.url}}" alt="Chicago" style="width:100%;">
         </div>

         <div class="item">
           <img src="{{car_details.car_image_internal2.url}}" alt="New york" style="width:100%;">
         </div>
       </div>

       <!-- Left and right controls -->
       <a class="left carousel-control" href="#myCarousel" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left"></span>
         <span class="sr-only">Previous</span>
       </a>
       <a class="right carousel-control" href="#myCarousel" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right"></span>
         <span class="sr-only">Next</span>
       </a>
     </div>
   </div>




                    <!--Info Column-->
                    <div class="info-column col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    	<div class="info-outer">
                        	<div class="upper-info">
                        		<div class="sidebar-title"><h3>{{car_details.brand}}-{{car_details.car_name}} </h3></div>
                            <hr>
                            {{car.id}}

                            	<ul class="list">
                                    <li><a href="#" class="clearfix"><span class="col">Transmission</span> <span class="col">{{car_details.transmission}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Airbags</span> <span class="col">{{car_details.air_bags}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Color</span> <span class="col">{{car_details.color}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Fuel Type</span> <span class="col">{{car_details.fuel_type}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Power</span> <span class="col">{{car_details.power_hp}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Seats</span> <span class="col">{{car_details.seats}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Avaiblility</span> <span class="col">{{car_details.is_available_car}}</span></a></li>
                                    <li><a href="#" class="clearfix"><span class="col">Model Year</span> <span class="col">{{car_details.model_year}}</span></a></li>
                                </ul>
                            </div>
                            <ul class="info clearfix">
                                <li> <span class="price"><strong>Price:</strong> </span></li>
                                <li> <span class="price"><strong>${{car_details.car_price}}</strong> / Week</span></li>
                            </ul>
                        </div>
                        <a href="{% url 'buggy_app:car_booking' %}?car={{car.id}}">Booking Now</a>


                        <a href="" class="theme-btn btn-style-one">BOOK a Car</a>

                    </div>

                </div>
            </div>
			<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-long-arrow-up"></span></div>



{% endblock %}

templates/buggy_app/car_list.html
{% extends "buggy_app/base.html" %}


{% block body_block %}
{% load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
<div class="container">





{% for car in cars %}



                        	<div class="car-info-block col-md-6 col-sm-6 col-xs-12">
                            	<div class="inner-box">
                                	<div class="image" >
                                    	<a href="{{car.id}}/"><img src="{{car.car_image.url}}" alt="" /></a>
                                    </div>
                                    <div class="lower-box">
                                    	<h3><a href={{car.id}}/>{{car.car_name}}</a></h3>
                                        <div class="more-info">
                                            <ul>
                                                <li>Brand: <span>{{car.brand}}</span></li>
                                                <li>Air Condition: <span>Yes</span></li>
                                                <li>Color: <span>{{car.color}}</span></li>
                                                <li>Transmission: <span>{{car.transmission}}</span></li>
                                            </ul>
                                            <div class="price-day">${{car.car_price}}<span>/Week</span></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                          {% endfor %}

                    {% endblock %}

templates/buggy_app/index.html
{% extends "buggy_app/base.html" %}


{% block body_block %}
{% load staticfiles %}
<div class="container">


<div id ="slides" class="carousel slide" data-ride="carousel">
<ul class="carousel-indicators">
  <li data-target="#slides" data-slide-to="0" class="active"></li>
  <li data-target="#slides" data-slide-to="1"></li>
  <li data-target="#slides" data-slide-to="2" ></li>
  <li data-target="#slides" data-slide-to="3" ></li>
  <li data-target="#slides" data-slide-to="4" ></li>
  <li data-target="#slides" data-slide-to="5" ></li>


</ul>
<div class="carousel-inner">

<div class="carousel-item active">
  <img src="{% static "img/nisan1.png" %}" >
  <div class="carousel-caption">
    <h1 class= "display-2">Join Buggy</h1>
    <button type="button" class="btn btn-outline-light btn-lg">Pricing</button>
    <button type="button" class="btn btn-primary btn-lg">Apply Now</button>
  </div>

</div>
<div class="carousel-item">
 <img src="{% static "img/nisan2.png" %}" >

</div>
<div class="carousel-item">
  <img src="{% static "img/sonatan.png" %}" >
</div>

<div class="carousel-item">
  <img src="{% static "img/nissan.png" %}" >
</div>
<div class="carousel-item">
  <img src="{% static "img/sonata.png" %}" >
</div>
<div class="carousel-item">
  <img src="{% static "img/uber.png" %}" >
</div>

</div>
</div>
</div>



<div class="container-fluid padding">
<div class="row jumbotron">
  <div class="row welcome text-center">



<div class="col-12">

<img src="{% static "img/bg.png" %}" class="img-fluid" alt="Responsive image">
</div>

  </div>


  </div>
  </div>







<div class="container-fluid padding">
<div class="row welcome text-center">
  <div class="col-12">
    <h1 class="display-4"> Why Buggy </h1>


</div>
<hr>

</div>
</div>



<div class=" container">
<div class="row text-center padding">

<div class="col-cs-12 col-sm-6 col-md-6 col-lg-3">

  <img src="{% static "img/no.jpg" %}" class="image-responsive"alt="No">
    <h3>No commitment</h3>
    <p>Return the car at any time! Just let us know two weeks in advance to allow for processing.</p>

</div>
<div class="col-cs-12 col-sm-6 col-md-6 col-lg-3">

  <img src="{% static "img/personal.jpg" %}" class="image-responsive"alt="No">
    <h3>Personal Use</h3>
    <p>Your car is your personal vehicle. Keep it 24 / 7 and use it for running errands, commuting, or any other personal tasks.</p>

</div>
<div class="col-cs-12 col-sm-6 col-md-6 col-lg-3">
  <img src="{% static "img/high.jpg" %}" class="image-responsive"alt="No">

    <h3>HIGH MILEAGE ALLOTMENT</h3>
    <p>Drive to your heart's content! Our rental package allows for unlimited mileage!</p>

</div>
<div class="col-cs-12 col-sm-6 col-md-6 col-lg-3">

  <img src="{% static "img/tlc.jpg" %}" class="image-responsive"alt="No">
    <h3>Tlc and Uber</h3>
    <p>Our vehicles are all registered and insured according to TLC regulations allowing you to start earning immediately.</p>

</div>

</div>
<hr class="my-4">
</div>



<div class="container-fluid padding">
<div class="row text-center padding">
  <div class="col-12">
    <h2>Coonect With Us</h2>

  </div>



  <div class="col-12 social padding">
      <a href="https://www.facebook.com/Buggy-LLC-444013566034861/"><i class="fab fa-facebook"></i></a>
        <a href="https://pk.linkedin.com/company/buggy-llc"><i class="fab fa-linkedin-in"></i></a>
          <a href="gmail.com/"><i class="fab fa-google-plus-g"></i></a>
    </div>


</div>
</div>
<footer>
<div class="container-fluid padding">
  <div class="row text-center">
    <div class="col-md-4">
      <img src="{% static "img/buggyc.png" %}"alt="buggylogo">
      <hr class="light">
      <p>718-705-4480</p>
      <p>buggy@joinbuggy.com</p>
      <p>St 389-391 EMPIRE BLVD </p>
      <p>BROOKLYN, NY 11225</p>

    </div>
    <div class="col-md-4">
      <hr class="light">
      <h5>Our Hours</h5>
      <hr class="light">
      <p> UTC Offset Standard Time : UTC -5H</p>
      <p>MONDAY – FRIDAY : 8:00AM – 6:00PM</p>
      <p>SATURDAY : CLOSED </p>
      <p>SUNDAY : 9:00AM -5:00PM</p>

    </div>
    <div class="col-md-4">
      <hr class="light">
      <h5>Services</h5>
      <hr class="light">
      <p>INFO FOR CURRENT DRIVERS -TEXT ONLY : 347-334-6313</p>
      <p>BILLING - TEXT ONLY : 347-334-6316</p>
      <p>MAINTENANCE -TEXT ONLY : 347-334-6314</p>
    </div>
    <div class="col-12">
      <hr class="light-100">
      <h5>© 2017 Buggy</h5>

    </div>
  </div>

</div>



</footer>

{% endblock %}